"""Allow null return_date in Borrow

Revision ID: 7bac6f61bdf2
Revises: 
Create Date: 2024-06-21 20:31:33.623644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bac6f61bdf2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrow', schema=None) as batch_op:
        batch_op.alter_column('return_date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrow', schema=None) as batch_op:
        batch_op.alter_column('return_date',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
